dist: build creates loop image
Signed-off-by: Stanislav Fomichev <stfomichev@yandex-team.ru>

diff --git a/dist/build b/dist/build
--- a/dist/build
+++ b/dist/build
@@ -2,78 +2,167 @@
 
 set -e
 
-set -- `getopt c $*`
-[ ! $? -eq 0 ] && { exit 1; }
+BINARY=$(basename $0)
+usage() {
+	echo "Usage: $BINARY [-d] [-v] <config>.conf"
+	echo
+	echo "Options:"
+	echo -e "\t-d\tClear image before and after build (dry-run)"
+	echo -e "\t-v\tShow underlying portoctl commands"
+	exit 1
+}
+
+set -- `getopt dvh $*`
+[ ! $? -eq 0 ] && { usage; }
 
 NEED_CLEAR=0
+VERBOSE=0
 while [ ! "$1" = "--" ]; do
 	case "$1" in
-	-c)
+	-d)
 		NEED_CLEAR=1
 		;;
+	-v)
+		VERBOSE=1
+		;;
 	*)
-		"Invalid argument $1"
+		usage
 		;;
 	esac
 	shift
 done
 shift
 
+say() { tput setaf 3; echo "$@"; tput sgr0; }
+
 CONFIG() {
 	REPO=$(cd $(dirname $0)/../ && pwd)
 	DIST=$REPO/dist
 	USER=stfomichev
-	ROOT=$DIST/$NAME
+	ROOT=$DIST/${NAME}.loop
+	TAR="$DIST/${NAME}.img"
+	LOOP_SIZE=8G
+	GET_TS=${ROOT}.get
+
+	CLEAR() {
+		[ $NEED_CLEAR -eq 1 ] || : && { rm -rf $ROOT $GET_TS; }
+	}
+
+	CLEAR
 
 	pctl() {
-		echo portoctl "$@"
-		sudo $REPO/portoctl "$@"
+		if [ $VERBOSE -eq 1 ]; then say portoctl "$@"; fi
+		$REPO/portoctl "$@"
+
+		## TODO: ask use to exec if fails
 	}
 
-	bootstrap() {
-		local tar="$DIST/${NAME}.img"
-		[ -f $tar ] || (cd $DIST && curl -L $URL > $tar)
-		[ -d $ROOT ] || (mkdir -p $ROOT && cd $ROOT && sudo tar xf $tar && sudo chown $USER:$USER $ROOT && sudo chmod 0755 $ROOT)
-	}
-
-	clone() {
-		[ -d $1 ] || {
-			mkdir -p $1
-			(cd $1 && git clone $REPO . && git submodule init && git submodule update)
+	download_image() {
+		[ -f $TAR ] || {
+			say "Download $URL"
+			(cd $DIST && curl -L $URL > $TAR)
 		}
 	}
 
-	CLEAR() {
-		[ $NEED_CLEAR -eq 1 ] && sudo rm -rf $ROOT || :
+	prepare_loop() {
+		say "Prepare loop $ROOT"
+		fallocate -l $LOOP_SIZE $ROOT
+		mkfs.ext4 -F -F $ROOT
+	}
+
+	pexec() {
+		pctl exec $NAME user="root" group="root" cwd="/" hostname="$NAME" "$@"
+	}
+
+	untar_image() {
+		local loop_dir="/tmp/__root__"
+		local tar_path="/tmp/__root_tar__"
+		local new_root="/tmp/__root_dir__"
+
+		pexec bind="$ROOT $loop_dir rw; $TAR $tar_path ro"  command="bash -c 'mkdir -p $new_root && mount $loop_dir $new_root && tar -xf $tar_path -C $new_root && sync'"
+	}
+
+	debootstrap() {
+		local dist=$1
+		shift
+		local url=$1
+		shift
+		local args="$*"
+		local loop_dir="/tmp/__root__"
+		local tar_path="/tmp/__root_tar__"
+		local new_root="/tmp/__root_dir__"
+
+		say "debootstrap $args $dist $url"
+
+		pexec bind="$ROOT $loop_dir rw"  command="bash -c 'mkdir -p $new_root && mount $loop_dir $new_root && cd $new_root && debootstrap $args $dist . $url && sync'"
+	}
+
+	clone() {
+		local loop_dir="/tmp/__root__"
+		local new_root="/tmp/__root_dir__"
+
+		pexec bind="$ROOT $loop_dir rw" command="bash -c 'mkdir -p $new_root && mount $loop_dir $new_root && mkdir -p $new_root/src && cd $new_root/src && git clone $REPO . && git submodule init && git submodule update && sync'"
+	}
+
+	SIZE() {
+		say "SIZE $1"
+		LOOP_SIZE=$1
+	}
+
+	valid_ts() { test -f $1 && return 1 || return 0; }
+	set_ts() { touch $1; }
+
+	DEBOOTSTRAP() {
+		say "DEBOOTSTRAP $*"
+
+		if ! valid_ts $GET_TS; then return; fi
+
+		prepare_loop
+		debootstrap "$@"
+		clone $ROOT/src
+		set_ts  $GET_TS
 	}
 
 	GET() {
+		say "GET $*"
 		URL=$1
 
-		CLEAR
+		if ! valid_ts $GET_TS; then return; fi
 
-		echo "Downloading image..."
-		bootstrap
-		echo "Preparing repository..."
+		download_image
+		prepare_loop
+		untar_image
 		clone $ROOT/src
+		set_ts  $GET_TS
 	}
 
-	RUN() { pctl exec $NAME root="$ROOT" cwd="/src" hostname="$NAME" command="$*"; }
+	RUN() {
+		say "RUN $*"
+
+		local tmp="$(mktemp)"
+		echo "#!/bin/sh" > $tmp
+		chmod +x $tmp
+
+		pexec root="$ROOT" cwd="/src" command="$*" bind="$tmp /sbin/initctlk ro" env="DEBIAN_FRONTEND=noninteractive"
+		rm $tmp
+	}
 
 	DEBUILD() {
-		echo "Packaging..."
+		say "DEBUILD"
+
 		stty sane
-		pctl exec $NAME command="debuild -i -us -uc -b $*" root="${ROOT}" cwd="/src"
+		pexec command="debuild -i -us -uc -b $*" root="${ROOT}" cwd="/src"
 	}
 
 	NOOP() {
-		echo "#!/bin/sh" | sudo tee $ROOT/$1
-		sudo chmod +x $ROOT/$1
+		pexec root="$ROOT" command="bash -c 'echo \"#!/bin/sh\" > $1 && chmod +x $1 && sync'"
 	}
 
 	INSTALL() {
-		sudo mkdir -p $ROOT/boot/grub/
-		sudo touch $ROOT/boot/grub/menu.lst
+		say "INSTALL"
+
+		RUN mkdir -p /boot/grub/
+		RUN touch /boot/grub/menu.lst
 		RUN apt-get install -y grub
 		NOOP /sbin/update-grub
 		NOOP /sbin/update-initramfs
@@ -93,7 +182,9 @@ CONFIG() {
 	}
 
 	SELFTEST() {
-		pctl exec porto command="./portod --stdlog --failsafe" root="${ROOT}" cwd="/src"
+		say "SELFTEST"
+
+		pexec command="./portod --stdlog --failsafe" root="${ROOT}" cwd="/src"
 	#	pctl run porto command="./portod" root="${ROOT}" cwd="/src"
 	#	pctl exec porto/selftest command="./portotest" root="${ROOT}" cwd="/src"
 	#	pctl destroy porto
@@ -101,10 +192,15 @@ CONFIG() {
 }
 
 CP() {
-	pctl exec $NAME root="$ROOT" hostname="$NAME" command="cp /tmp/__copy_me__ '$2'" bind="$1 /tmp/__copy_me__ ro"
+	say "COPY $1 -> $2"
+
+	local copy_bind="/tmp/__copy_me__"
+	pexec root="$ROOT" command="cp $copy_bind $2" bind="$1 $copy_bind ro" bind_dns=false
 }
 
 ECHO() {
+	say "ECHO $1"
+
 	local file="$1"
 	local tmp="$(mktemp)"
 	cat > $tmp
@@ -113,6 +209,8 @@ ECHO() {
 }
 
 REPO() {
+	say "REPO $1 $2"
+
 	local file="$1"
 	shift
 	local url="$1"
@@ -137,7 +235,9 @@ if [ $# -ge 1 ]; then
 		fi
 		CONFIG $NAME
 
-		. $conf
+		file="$conf"
+		if [ -f "./$conf" ]; then file="./$conf"; fi
+		. $file
 	done
 else
 	for conf in ./*.conf; do
