dist: install package
Signed-off-by: Stanislav Fomichev <stfomichev@yandex-team.ru>

diff --git a/dist/build b/dist/build
--- a/dist/build
+++ b/dist/build
@@ -35,7 +35,6 @@ CONFIG() {
 		echo portoctl "$@"
 		sudo $REPO/portoctl "$@"
 	}
-	pexec() { pctl exec $NAME root="$ROOT" cwd="/src" hostname="$NAME" command="$*"; }
 
 	bootstrap() {
 		tar="$DIST/${NAME}.img"
@@ -65,14 +64,37 @@ CONFIG() {
 		clone $ROOT/src
 	}
 
-	RUN() {
-		pexec "$@"
-	}
+	RUN() { pctl exec $NAME root="$ROOT" cwd="/src" hostname="$NAME" command="$*"; }
 
 	DEBUILD() {
 		echo "Packaging..."
 		stty sane
 		pctl exec $NAME command="debuild -i -us -uc -b $*" root="${ROOT}" cwd="/src"
+	}
+
+	NOOP() {
+		echo "#!/bin/sh" | sudo tee $ROOT/$1
+		sudo chmod +x $ROOT/$1
+	}
+
+	INSTALL() {
+		sudo mkdir -p $ROOT/boot/grub/
+		sudo touch $ROOT/boot/grub/menu.lst
+		RUN apt-get install -y grub
+		NOOP /sbin/update-grub
+		NOOP /sbin/update-initramfs
+
+		RUN apt-get install -y --force-yes linux-image-server linux-image-3.10.59-19 linux-firmware wireless-crda crda libnl-3-200 libnl-genl-3-200 wireless-regdb linux-tools linux-headers-3.10.59-19 kexec-tools anacron makedumpfile libdw1
+
+		RUN apt-get install -y --force-yes logrotate yandex-search-group-porto
+		RUN dpkg -i /yandex-porto_*_amd64.deb
+		RUN apt-get install -y --force-yes python-central python-protobuf
+		RUN dpkg -i /python-portopy_*_all.deb
+
+		# make sure package is installed
+		for binary in portod portoctl portotest; do
+			RUN which $binary || { echo "ERROR: Can't find $binary"; exit 1; }
+		done
 	}
 
 	SELFTEST() {
