mkimg: use non-interactive debconf frontend
Signed-off-by: Stanislav Fomichev <stfomichev@yandex-team.ru>

diff --git a/scripts/mkimg b/scripts/mkimg
--- a/scripts/mkimg
+++ b/scripts/mkimg
@@ -73,7 +73,7 @@ bootstrap() {
 	local conf=$2
 
 	local tmpdir=$(mktemp -d)
-	pctl exec $CONTAINER command="bash -c 'mount $image $tmpdir && $conf bootstrap $tmpdir; ret=$?; umount $image; exit $ret'" user=root group=root bind_dns=false #root_readonly=true debootsrap chroot fails
+	pctl exec $CONTAINER command="bash -c 'mount $image $tmpdir && $conf bootstrap $tmpdir; ret=\$?; umount $image; exit \$ret'" user=root group=root bind_dns=false env="DEBIAN_FRONTEND=noninteractive" #root_readonly=true debootsrap chroot fails
 	rmdir $tmpdir
 }
 
@@ -93,8 +93,8 @@ prepare() {
 
 	pctl run $CONTAINER command="/sbin/init" root="$image" hostname="$CONTAINER" user=root group=root bind="$conf /config ro; $bind_selinux; $bind_porto" bind_dns=false allowed_devices="$ALLOWED_DEVICES"
 
-	pctl exec ${CONTAINER}/prepare command="bash -c '/config prepare'" isolate=false user=root group=root
-	pctl exec ${CONTAINER}/sync command="bash -c 'sync'" isolate="false" user=root group=root
+	pctl exec ${CONTAINER}/prepare command="bash -c '/config prepare'" isolate=false user=root group=root env="DEBIAN_FRONTEND=noninteractive"
+	pctl exec ${CONTAINER}/sync command="bash -c 'sync'" isolate="false" user=root group=root env=" DEBIAN_FRONTEND=noninteractive"
 
 	[ -z "$CHECK" ] || check
 
